---
- name: add multiple users
  hosts: db
  become: yes
  vars: 
    dbusers:
      - username: victor
        pass: pass1
      - username: Rita 
        pass: pass2
      - username: Guilene
        pass: pass3
  tasks: 
    - name: add users
      user:     
        name: "{{ item.pass }}"
      loop: "{{ dbusers }}" 