---
- name: first play
  hosts: all 
  become: yes
  tasks:
    - name: install tmux
      package:
        name: tmux
        state: present 
    - name: create an archive
      archive:
        path: /var/log
        dest: /tmp/logs.tar.gz
        format: gz     

- name: second play
  hosts: ws
  become: yes
  tasks: 
    - name: install git -y
      yum:
        name: git
        state: present
      tags: git  

- name: third play
  hosts: db
  become: yes
  tasks:
     - name: Update apt cache
       apt:
        update_cache: yes

     - name: Install Apache
       apt:
         name: apache2
         state: present

     - name: Ensure Apache is running
       service:
         name: apache2
         state: started
         enabled: yes