---
- hosts: wind
  tasks:
    - name: Create a directory
      win_file:
        path: C:\Users\Administrator\Desktop\Guilene1
        state: directory
    - name: download file online 
      win_get_url:
        dest: C:\Users\Administrator\Desktop\Guilene1
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.3.tar.xz
    - name: install all update
      win_updates:
        category_names: '*'
        reboot: true